<a href="https://colab.research.google.com/github/Jagroop2001/PyTorch-Learning/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [ ]:
import torch
print(torch.__version__)

2.1.0+cu118


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introductions to  Tensor's

### Creating Tensor's

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,13])
vector

tensor([ 7, 13])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[1,2],[3,2]])
MATRIX

tensor([[1, 2],
        [3, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0705, 0.8067, 0.6079, 0.8129],
        [0.7768, 0.9471, 0.2820, 0.6004],
        [0.9765, 0.8759, 0.4372, 0.7176]])

In [ ]:
# Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height , width, color channel (RGB)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Creating a tensor of all zeros
zero = torch.zeros(size=(2,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Creating a tensor of all ones
zero = torch.ones(size=(4,3))
zero

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Uee torch.range()
one_to_ten = torch.arange(1,11)

In [ ]:
torch.arange(1,11,step=2)

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0,2.0,4.0], dtype=None,
                               device=None, # what devide is your tensor or (cpu , gpu etc)
                               requires_grad=False) # whether or not to track gradients or not
float_32_tensor

tensor([3., 2., 4.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 2, 4], dtype=torch.int32)

### Getting Information from tensors

1. Tensors have no right datatype - use `tensor.dtype`
2. Tensors have not right shape - use `tensor.shape`
3. Tensors have on the right device - use `tensor.device`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9820, 0.3826, 0.4552, 0.9794],
        [0.0212, 0.6863, 0.7986, 0.1333],
        [0.1398, 0.0328, 0.5256, 0.3167]])

In [ ]:
# Find out details about some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors ( tensor operations)

It includes :
- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplication

In [ ]:
tensor_one = torch.tensor([1,2,3])
tensor_one+100

tensor([101, 102, 103])

In [ ]:
tensor_one*10

tensor([10, 20, 30])

In [ ]:
tensor_one-10

tensor([-9, -8, -7])

In [ ]:
# PyTorch in-built functions
torch.mul(tensor_one,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor_one,10)

tensor([11, 12, 13])

In [ ]:
# Matrix multiplications (dot product)

torch.matmul(tensor_one, tensor_one)

tensor(14)

### Rules needs to satisfy while matrix multiplication :
1. Inner dimensions must match.
* `(3,2)` @ `(3,2)` won't work
* `(3,2)` @ `(2,3)` will work

2. Resulting shape has shape of outer dimension
* `(3,2)` @ `(2,3)` will work and resulting shape is `(3,3)`

### To fix out tensor shape issue, we can use Transpose of a matrix

In [ ]:
matrix_A = torch.tensor([[1,2],[3,4],[5,6]])
matrix_B = torch.tensor([[0,4],[9,6],[7,8]])

matrix_A.shape, matrix_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(matrix_A,matrix_B.T)

tensor([[ 8, 21, 23],
        [16, 51, 53],
        [24, 81, 83]])

### Finding min, max, mean, sum etc. (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

### Reshaping, Stacking, Sueezing and unsqueezing

- Rehaping - reshapes an input tensor to defined shape.
- View - Return a view of an input tensor of certain shape but keep the same memory as he original tensor.
-Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
-Squeeze - remove all `1` dimension from a tensor
-Unsqueeze - add a `1` dimension to a target tensor.
-Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x.shape

torch.Size([9])

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_rehaped = x.reshape(1,9)
x_rehaped, x_rehaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_rehaped = x.reshape(3,3)
x_rehaped, x_rehaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view ( changing z, changes x)
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(3,3)
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z[:,0] = 1000
z,x

(tensor([[1000.,    2.,    3.],
         [1000.,    5.,    6.],
         [1000.,    8.,    9.]]),
 tensor([1000.,    2.,    3., 1000.,    5.,    6., 1000.,    8.,    9.]))

In [ ]:
# stack tensors
x_Stack = torch.stack([x,x,x,x],dim=1)
x_Stack.shape

torch.Size([9, 4])

In [ ]:
## squeeze
a = torch.zeros(2,2,1,1,2)
a.shape

torch.Size([2, 2, 1, 1, 2])

In [ ]:
b = torch.squeeze(a)
b.shape

torch.Size([2, 2, 2])

In [ ]:
# unsqueeze
c = b.unsqueeze(dim=1)
c.shape

torch.Size([2, 1, 2, 2])

In [ ]:
torch.permute(c , (1,0,2,3)).shape

torch.Size([1, 2, 2, 2])

### Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
# Numpy array to tensor
array = np.arange(1,9)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
#Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### PyTorch Reproducbility




In [ ]:
# set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

A = torch.rand(2,3)
torch.manual_seed(RANDOM_SEED)
B = torch.rand(2,3)

A,B, A==B

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[True, True, True],
         [True, True, True]]))